### ISSUE TITLE
switch to the develop branch as default

### ISSUE THREAD

**Issue by mrexodia** [zyantific/zyan-disassembler-engine#11]
Currently it is very confusing that the master uses C++14 and develop uses C99. Maybe it's a good idea to switch to the develop as the default branch.

**Comment by athre0z** [comment]
v2.0 (what you see in develop) is still in development and currently not suitable for production use. People tend to checkout and use whatever is defined as default branch and right now, that wouldn't be a good idea at all. Some major changes in operand decoding (and thus the public interface) and especially encoding are still ahead, also we're even considering to rename the whole project in order to reflect that it's no longer just a disassembler. Right now, we prefer people to still use the C++ (v1.0) version.

**Comment by mrexodia** [comment]
Okay, could you upload the instruction editor as a binary somewhere though?
I want to try this version but I'm missing the generated opcode files.

**Comment by athre0z** [comment]
Mhh, I don't have an up-to-date binary at hand right now either, but compilation probably failed because of the missing encoder table anyways, which currently isn't generated by the instruction editor, but by a temporary Python script.

I pushed a change to develop that allows compilation by updating the CMake defaults and disabling the encoder. If you're interested in that part of the lib, I pasted you the encoder table here:
https://gist.github.com/athre0z/b55273c2106904981c77265ef8ea626d

**Comment by mrexodia** [comment]
After installing all the components/packages/whatever in Delphi XE8 I get the following errors compiling:

```
[dcc32 Error] formMain.pas(934): E2003 Undeclared identifier: 'AccessMode'
[dcc32 Error] formMain.pas(962): E2003 Undeclared identifier: 'AccessMode'
[dcc32 Error] formMain.pas(962): E2003 Undeclared identifier: 'TOperandAccessMode'
```

But thanks a lot! I'm mainly interested in the decoder and I plan to run the capstone tests to see how this stacks up. My main interest in the InstructionEditor was just to play around and see if I can figure out how it works.

**Comment by mrexodia** [comment]
Okay I found the problem, `AccessMode` was renamed to `Action`. I'll send a PR later.

**Comment by athre0z** [comment]
Nice, thanks! Please keep in mind that everything you see isn't final, yet. I guess it'll take us another month or two to get to beta state. Besides the operand rework, we're currently developing tests to further optimize the tables and to diff against the "tables" from XED in order to eliminate errors and further tweak our own ones.
