### ISSUE TITLE
bug in printing addresses

### ISSUE THREAD

**Issue by mrexodia** [zyantific/zyan-disassembler-engine#13]
In [Formatter.c:ZydisFormatterPrintAddressIntel](https://github.com/zyantific/zyan-disassembler-engine/blob/develop/src/Formatter.c#L396) in 32 and 64 bit mode addresses will be incorrectly printed if they sign-extend to a negative integer. I'm still trying to figure out why this happens.

```
rasm2 -a x86.zyan -b 32 -d E8FFFFFFFF
call 0xFFFFFFFFFFFFFFFF
```

**Comment by athre0z** [comment]
I think it's a bug in the decoder, not the formatter. Looks like the final `+ instructionLength` on the immediate for relative instructions isn't performed.

**Comment by athre0z** [comment]
I pushed a commit. I'll have to talk to @flobernd to discuss whether this is the best way of handling that, but it resolves the issue for now.

**Comment by mrexodia** [comment]
Thanks 👍

**Comment by flobernd** [comment]
I reverted the changes to the decoder, because I think the operand-info struct should always reflect the raw operand values without any adjustments (relative address-offset in this case).

The actual bug was located in ``ZydisUtilsCalcAbsoluteTargetAddress`` where I forgot to properly add the instruction-length.
